services:
  postgres:
    image: postgres
    container_name: bms-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bms
      POSTGRES_USER: bms
      POSTGRES_PASSWORD: change_me!
    ports:
      - "5432:5432"
    volumes:
      - core_banking_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  core_banking_pgdata:
